title: UFPA - LINCE
description: Site LINCE - Prof. Raphael Teixeira.
theme: just-the-docs

url: https://raphateixeira.github.io

logo: "/imgs/logoufpa.png"

footer_content: "UFPA - Raphael Teixeira 2023"


