title: UFPA - raphateixeira
description: Site Prof. Raphael Teixeira!
theme: just-the-docs

url: https://raphateixeira.github.io

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
