title: [Raphael Teixeira]
subtitle: [UFPA-CAMTUC]
description: [UFPA-CAMTUC-FEE]
remote_theme: just-the-docs/just-the-docs
color_scheme: "light"
#search_enabled: false
plugins:
  - jekyll-default-layout

