title: [Raphael Teixeira]
description: [UFPA-CAMTUC-FEE]
url: https://raphateixeira.github.io/
remote_theme: just-the-docs/just-the-docs
color_scheme: "light"
logo: "/img/logoUFPA.png"
search_enabled: false

plugins:
  - jekyll-default-layout

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"