---
title: "Reposotórios GitHub"
date: "02/12/2025"
categories: [Notícias, Pesquisa, Financiamento]
---

### Repositórios:

[GAN-MNIST](https://github.com/kroosen/GAN-in-keras-on-mnist): Utiliza redes GAN para gerar imagens de dígitos manuscritos.

[Controle II](https://github.com/rsbayma/Controle-II): Repositório com códigos e materiais relacionados à disciplina de Controle II - Prof. Rafael Bayma.

[SINDy-RL](https://github.com/raphateixeira/sindy-rl): Combina SINDy com aprendizado por reforço para controle de sistemas dinâmicos.

[RL-Projects](https://github.com/swagatk/RL-Projects-SK): Repositório com diversos projetos de aprendizado por reforço implementados em Python.

[Marcelino UNB](https://github.com/marcelinoandrade/UNB): Repositório com materiais e códigos relacionados a projetos do Prof. Marcelino Andrade da Universidade de Brasília.

[Transformer MPC](https://github.com/BYU-PRISM/Transformer_MPC): Implementação de controle preditivo baseado em transformadores para sistemas dinâmicos.

[Clear RL](https://github.com/vwxyzjn/cleanrl): Repositório com implementações simples e eficientes de algoritmos de aprendizado por reforço em PyTorch.

[Carbon Clips](https://github.com/chavarera/py-carbon-clips): Ferramenta para criar clipes de carbono em Python, útil para visualização de dados e simulações.

[DSO](https://github.com/dso-org/deep-symbolic-optimization): Framework para otimização simbólica profunda, combinando aprendizado de máquina com métodos simbólicos.

[PySR](https://github.com/MilesCranmer/PySR): Biblioteca para descoberta de equações simbólicas usando algoritmos genéticos e aprendizado de máquina.

[SD-VAE](https://github.com/stathius/sd-vae): 

[MPC-Pendulum-Python](https://github.com/simorxb/MPC-Pendulum-Python): Implementação de controle preditivo para o problema do pêndulo invertido em Python.

[Reinforcement-Learning-in-Process-Control](https://github.com/emedd33/Reinforcement-Learning-in-Process-Control): Aplicações de aprendizado por reforço em controle de processos industriais.

[Series Temporais](https://github.com/IvanildoBatista/Series-Temporais): Repositório com materiais e códigos para análise e modelagem de séries temporais.

[SinDyAutoEncoders](https://github.com/kpchamp/SindyAutoencoders): Combina SINDy com autoencoders para modelagem de sistemas dinâmicos complexos.

[MeNum](https://github.com/karo-txs/MeNum): Biblioteca para métodos numéricos em Python, focada em aplicações de engenharia e ciência de dados.

[Kronic](https://github.com/eurika-kaiser/KRONIC)

[PINN2ODe](https://github.com/PML-UCF/pinn_ode_tutorial): Tutorial sobre o uso de Redes Neurais Informadas pela Física (PINNs) para resolver equações diferenciais ordinárias (ODEs).

[SindyMPC](https://github.com/eurika-kaiser/SINDY-MPC): Combina SINDy com controle preditivo para sistemas dinâmicos.